#!/usr/bin/env bash
# Синхронизирует samples.go из основного проекта network_monitor.
# Источник правды: backend/internal/parser/samples.go
#
# Приоритет:
#   1) LOCAL_SAMPLES=/path/to/samples.go
#   2) соседний клон ../network_monitor/.../samples.go (от корня репо)
#   3) RAW URL с GitHub
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RAW="${RAW:-https://raw.githubusercontent.com/varlahin-gena/network_monitor/main/backend/internal/parser/samples.go}"
LOCAL_CANDIDATE="${LOCAL_SAMPLES:-}"
if [ -z "$LOCAL_CANDIDATE" ]; then
  LOCAL_CANDIDATE="$REPO_ROOT/../network_monitor/backend/internal/parser/samples.go"
fi

DST_DIR="$(cd "$SCRIPT_DIR/../gen/samplesrc" && pwd)"
mkdir -p "$DST_DIR"
DST="$DST_DIR/samples.go"
TMP="$DST.tmp"
SOURCE_LABEL=""

log()  { echo "[+] $*"; }
warn() { echo "[!] $*"; }

copy_local_samples() {
  local path="$1"
  if [ -s "$path" ]; then
    echo ">> using local $path"
    cp "$path" "$TMP"
    SOURCE_LABEL="$path"
    return 0
  fi
  return 1
}

download_samples() {
  local attempt=1
  local max_attempts=4
  local delay=5

  while [ "$attempt" -le "$max_attempts" ]; do
    echo ">> fetching $RAW (attempt $attempt/$max_attempts)"
    if curl -fL --connect-timeout 20 --max-time 120 --retry 2 --retry-delay 3 \
      --retry-all-errors -o "$TMP" "$RAW"; then
      SOURCE_LABEL="$RAW"
      return 0
    fi

    if [ "$attempt" -lt "$max_attempts" ]; then
      warn "не удалось скачать samples.go; жду ${delay}s и пробую снова"
      sleep "$delay"
      delay=$((delay * 2))
    fi
    attempt=$((attempt + 1))
  done

  return 1
}

use_existing_samples() {
  if [ -s "$DST" ]; then
    warn "не удалось получить свежий samples.go; использую встроенный $DST"
    warn "это не мешает установке, но samples могут быть не самыми свежими"
    return 0
  fi
  return 1
}

if ! copy_local_samples "$LOCAL_CANDIDATE"; then
  if ! download_samples; then
    rm -f "$TMP"
    if use_existing_samples; then
      exit 0
    fi
    warn "не удалось получить samples.go и локальной копии нет"
    exit 1
  fi
fi

# 1) переименовываем пакет, чтобы подключить как подпакет генератора
sed -i 's/^package parser/package samplesrc/' "$TMP"

# 2) генеренный код помечаем, чтобы не редактировали руками
{
  echo "// Code generated by sync-samples.sh. DO NOT EDIT."
  echo "// source: $SOURCE_LABEL"
  echo
  cat "$TMP"
} > "$DST"
rm -f "$TMP"

log "written to $DST (from $SOURCE_LABEL)"
echo ">> проверь сборку: (cd $(dirname "$DST")/.. && go build ./...)"
echo "!! Если файл ссылается на типы пакета parser (не только строки),"
echo "   потребуется ручная правка импортов в $DST."
