#!/usr/bin/env bash
# Синхронизирует samples.go из основного проекта network_monitor.
# Источник правды: backend/internal/parser/samples.go
set -euo pipefail

RAW="https://raw.githubusercontent.com/varlahin-gena/network_monitor/main/backend/internal/parser/samples.go"
DST_DIR="$(cd "$(dirname "$0")/../gen/samplesrc" && pwd 2>/dev/null || echo "$(dirname "$0")/../gen/samplesrc")"
mkdir -p "$DST_DIR"
DST="$DST_DIR/samples.go"

echo ">> fetching $RAW"
curl -fsSL "$RAW" -o "$DST.tmp"

# 1) переименовываем пакет, чтобы подключить как подпакет генератора
sed -i 's/^package parser/package samplesrc/' "$DST.tmp"

# 2) генеренный код помечаем, чтобы не редактировали руками
{ echo "// Code generated by sync-samples.sh. DO NOT EDIT."; echo "// source: $RAW"; echo; cat "$DST.tmp"; } > "$DST"
rm -f "$DST.tmp"

echo ">> written to $DST"
echo ">> проверь сборку: (cd $(dirname "$DST")/.. && go build ./...)"
echo "!! Если файл ссылается на типы пакета parser (не только строки),"
echo "   потребуется ручная правка импортов в $DST."
